### ISSUE TITLE
Only one model download

### ISSUE THREAD

**Issue by Pamposgsk** [Padocia/Laravel-Nova-Pdf#11]
Hi,
In your preview photo shows that you are able to select multiple files simultaneously.
If i select more than one rows it just download the pdf that produced from the first model and ignore the others.
Am i doing something wrong?

Thanks for your package
Pampos

**Comment by Padocia** [comment]
Hello,
Make sure that you are looping through the `$models` variable in your template file to acess the selected rows model
Here's an example :  [resources/views/template.blade.php](https://github.com/Padocia/Laravel-Nova-Pdf/blob/master/resources/views/template.blade.php)
