### ISSUE TITLE
Append other pdf

### ISSUE THREAD

**Issue by warksit** [Padocia/Laravel-Nova-Pdf#12]
Is there a simple way to append disk stored pdf file(s) to the generated file?

**Comment by Padocia** [comment]
The only simple way I can think of now is to override the `saveAsPdf` function in your action and force it to merge the PDF's before saving.
Here's an example using [grofgraf/laravel-pdf-merger](https://packagist.org/packages/grofgraf/laravel-pdf-merger) package to merge the PDF's

```php
    protected function saveAsPdf()
    {
        $this->browsershot = $this->browsershot->html($this->renderView());

        $this->handleBrowsershotOptions();

        $pdf_rendered = $this->browsershot->pdf();
        $pdf_to_append = Storage::disk('local')->path('append.pdf');

        $merger = \PDFMerger::init();
        $merger->addPDFString($pdf_rendered);
        $merger->addPathToPDF($pdf_to_append);
        $merger->merge();
        $pdfFileContent = $merger->string();

        Storage::disk($this->getDisk())->put($this->getFilename(), $pdfFileContent);

        return $this;
    }

```

**Comment by warksit** [comment]
Thank you for your prompt and helpful reply. I ended up using the dev-master branch of [Webklex/laravel-pdfmerger](https://github.com/Webklex/laravel-pdfmerger) rather than grofgraf/laravel-pdf-merger due to a PSR-4 issue.

I really appreciate the time saving of the pointer you gave.
