### ISSUE TITLE
live site pdf zero

### ISSUE THREAD

**Issue by anditsung** [Padocia/Laravel-Nova-Pdf#8]
i install it on live site. but after the download the size is zero.

**Comment by Padocia** [comment]
do you have this problem only on live site ? is it working fine in development environment ?

**Comment by anditsung** [comment]
Yes. Only happen on live site. Dont have any problem on development

**Comment by Padocia** [comment]
did you run `npm install puppeteer` on live server ?

**Comment by anditsung** [comment]
yes, already install puppeteer. but after produce will have zero pdf.

**Comment by Padocia** [comment]
email me at `zakaria.tayebbey@gmail.com`

**Comment by anditsung** [comment]
mail you the file that was generated?
