### ISSUE TITLE
Some Tailwind classes not loaded

### ISSUE THREAD

**Issue by dualklip** [Padocia/Laravel-Nova-Pdf#9]
Hi there!

I'm trying to use some Tailwind classes to customize background colors or text colors, but doesn't been reflected in the PDF. Others classes like `text-2xl` or `font-extrabold` are ok, but if you try to use `bg-purple-300` nothing happen.

```blade
<!doctype html>
<html>
<head>
    <title>Laravel Nova Pdf Template</title>
    <meta charset="UTF-8"/>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @foreach ($stylesContents as $stylesContent)
        <style>
            {{ $stylesContent }}
        </style>
    @endforeach
    <style>
        html, body {
            height: 100%;
        }
    </style>
</head>
<body class="tailwind-container">
<section>
    @foreach ($models as $model)
        <div class="grid grid-cols-4 gap-4">
            <div class="bg-purple-300 h-12 rounded-md flex justify-center items-center text-white text-2xl font-extrabold">{{ $model->getKey() }}</div>
            <div class="bg-purple-300 h-12 rounded-md flex justify-center items-center text-white text-2xl font-extrabold">{{ $model->batch->name }}</div>
            <div class="bg-purple-300 h-12 rounded-md flex justify-center items-center text-white text-2xl font-extrabold">{{ $model->telephone->telephone }}</div>
            <div class="bg-purple-300 h-12 rounded-md flex justify-center items-center text-white text-2xl font-extrabold">{{ $model->status->name }} ({{ $model->status->code }})</div>
        </div>
    @endforeach
</section>
</body>
</html>
```

As you can see the template has been simplifies as max as possible in order to don't have any conflictive CSS class

This is the result that I can see in my PDF
![Captura de pantalla 2021-05-09 a las 12 08 05](https://user-images.githubusercontent.com/2706500/117568191-55d1ff80-b0bf-11eb-9644-e8487f9703f4.png)

**Comment by wcdev1288** [comment]
Were you able to figure this out? I'm running into the same issue. 
It might be puppeteer related:
- https://stackoverflow.com/questions/60736354/puppeteer-not-rendering-color-background-color-when-i-try-to-save-pdf-on-disk
- https://stackoverflow.com/questions/57373194/headless-chrome-not-detecting-css-and-background-image-of-the-webpage

**Comment by wcdev1288** [comment]
UPDATE: Looks like by default Browsershot has $showBackground = false;
Set it to true and your background should render. The issue I have now is that the handleBrowsershotOptions() is not passing the options.

protected function handleBrowsershotOptions()
{
    $this->browsershot->$showBackground();

    return $this;
}

`namespace Spatie\Browsershot;
...
/** @mixin \Spatie\Image\Manipulations */
class Browsershot
{
...
    protected $showBackground = false;
    protected $showScreenshotBackground = true;`

**Comment by Padocia** [comment]
handleBrowsershotOptions() issue is [#Fixed](https://github.com/Padocia/Laravel-Nova-Pdf/commit/7f6bc6fc8584678ff0cef790d500a1d36b3f48bb) in latest release

Change your code to : 
 ```php
protected function handleBrowsershotOptions()
{
     $this->browsershot = $this->browsershot->showBackground();
 
     return $this;
 }
 ```
